### ISSUE TITLE
"Unfork" kiwi.js?

### ISSUE THREAD

**Issue by joshuahhh** [IjzerenHein/kiwi.js#12]
This repo is a fork of nucleic/kiwi. Since that's a C++ implementation, it seems unlikely that there will be any PRs going back and forth, so I'm not sure if there's a continued purpose to having this relationship.

Ordinarily I wouldn't care, but apparently GitHub doesn't let you search in forks? So that's annoying. Not a huge deal though.

FWIW, it looks like the way to do this is to contact GitHub support (https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting).

Thanks!

**Comment by IjzerenHein** [comment]
Hey Joshua. Well I've dropped a note at Github support asking them to Unfork this repo. Fingers crossed.
cheers, Hein

**Comment by IjzerenHein** [comment]
Woohoo, kiwi.js has been unforked :)
