### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Rheeseyb** [IjzerenHein/kiwi.js#3]
I'm pretty sure this issue is purely down to not knowing which version of Typescript you were using to build this.
I've tried building using the version number in the `package.json` file, (by changing [this line](https://github.com/IjzerenHein/kiwi.js/blob/master/Gruntfile.js#L57) of the gruntfile to use `node_modules/.bin/tsc`, but that throws up the following error:
```
$ grunt
Running "exec:build" (exec) task
error TS6082: Only 'amd' and 'system' modules are supported alongside --out.
>> Exited with code: 2.
>> Error executing child process: Error: Command failed: node_modules/.bin/tsc --noImplicitAny -m commonjs -d -out lib/kiwi.js src/kiwi.ts
Warning: Task "exec:build" failed. Use --force to continue.

Aborted due to warnings.
```

So I tried then removing `-m commonjs` (as that's what the above seems to be complaining about), but then I can't use the project, and there is still an error trying to generate the docs (`tmp/kiwi-no-internal-modules.js: Unexpected token }` when running jsdoc2md)

**Comment by IjzerenHein** [comment]
Hi Rheese. Honestly, I don't know either. This is my only typescript project and I am not too well versed in the TypeScript build system. It sounds like something that is easy to fix but I unfortunately I don't have the time at the moment to take a look a this. Any PR's are very welcome.

**Comment by orentrutner** [comment]
Submitted a proposed PR #4. It includes @Rheeseyb's two changes and adds a fix for the doc error. It allows for a clean build and seems to work fine (I tried with just one app though.)

**Comment by IjzerenHein** [comment]
Thanks @orentrutner ! The build system has been upgraded and you can now use `npm run build` to build the code and docs.

@Rheeseyb Let me know whether this resolves your problem and whether this can be closed?

cheers
